name: API Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - services/login-api
          - services/chat-api

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Lint API workspace
        run: npm run lint --workspace ${{ matrix.service }}

      - name: Run unit tests
        run: npm run test:unit --workspace ${{ matrix.service }}

      - name: Run integration tests with Firestore emulator
        run: npx firebase emulators:exec --only firestore "npm run test:integration --workspace ${{ matrix.service }}"
