name: API Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: services/login-api
            image: login-api
          - service: services/chat-api
            image: chat-api

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Lint API workspace
        run: npm run lint --workspace ${{ matrix.service }}

      - name: Run unit tests
        run: npm run test:unit --workspace ${{ matrix.service }}

      - name: Run integration tests with Firestore emulator
        run: npx firebase emulators:exec --only firestore "npm run test:integration --workspace ${{ matrix.service }}"

      # NOTE: Uncomment the Docker build + containerized test steps below once we want CI to
      # execute the suite inside the production image for runtime parity.
      # - name: Build production Docker image
      #   run: |
      #     docker build \
      #       -f ${{ matrix.service }}/Dockerfile \
      #       -t ${{ matrix.image }}:ci \
      #       ${{ matrix.service }}

      # - name: Build tester Docker image
      #   run: |
      #     docker build \
      #       --target tester \
      #       -f ${{ matrix.service }}/Dockerfile \
      #       -t ${{ matrix.image }}:tester \
      #       ${{ matrix.service }}

      # - name: Run unit tests inside Docker image
      #   run: |
      #     docker run --rm \
      #       --entrypoint bash \
      #       ${{ matrix.image }}:tester \
      #       -lc "npm run test:unit"

      # - name: Run integration tests inside Docker image
      #   run: |
      #     docker run --rm \
      #       --entrypoint bash \
      #       ${{ matrix.image }}:tester \
      #       -lc "npx firebase emulators:exec --only firestore 'npm run test:integration'"
