name: API Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint API workspace
        run: npm run lint --workspace services/api

      - name: Run unit tests
        run: npm run test --workspace services/api

      - name: Run integration tests with Firestore emulator
        run: npx firebase emulators:exec --only firestore "npm run test:integration --workspace services/api"
