name: Terraform Checks

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-checks.yml'
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-checks.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_TERRAFORM_SA_EMAIL }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Terraform format check
        working-directory: infra
        run: terraform fmt -check -recursive

      - name: Initialize TFLint plugins
        working-directory: infra
        run: tflint --init

      - name: TFLint
        working-directory: infra
        run: tflint --recursive

      - name: Terraform init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: infra
        run: terraform validate -no-color

      - name: Terraform plan (drift detection)
        id: plan
        working-directory: infra
        continue-on-error: true
        run: |
          set -o pipefail
          terraform plan -detailed-exitcode -no-color
          exitcode=$?
          echo "exitcode=$exitcode" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Fail if terraform plan failed
        if: steps.plan.outputs.exitcode == '1'
        run: |
          echo "Terraform plan encountered an error."
          exit 1

      - name: Fail if terraform plan detected drift
        if: steps.plan.outputs.exitcode == '2'
        run: |
          echo "Terraform plan detected drift. Apply locally before merging."
          exit 1
