name: Web Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Lint web workspace
        run: npm run lint --workspace apps/web

      - name: Run frontend unit tests
        run: npm run test --workspace apps/web -- --run --reporter=dot
